config/routes.rb
Rails.application.routes.draw do
  root :to => "cocktails#index"
  resources :cocktails, only: [:index, :new, :create, :show] do
    resources :doses, only: [:create, :destroy], shallow:true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true


end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates :ingredient, :uniqueness => { :scope => :cocktail}

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :doses, dependent: :restrict_with_exception

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def show
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if
      @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end


   private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_doses, only: [:destroy]
  before_action :find_cocktail, only: [:new, :create, :destroy]


  def create
    @dose = @cocktail.doses.new(dose_params)
    if
      @dose.save
      redirect_to @cocktail
    else
      render 'cocktails/show'
    end
  end

  def destroy
    find_doses
    @dose.destroy
    redirect_to @dose.cocktail
  end

  private


  def find_doses
    @dose = Dose.find(params[:id])
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end


  def cocktail_params
    params.require(:dose).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktail#create</h1>
<p>Find me in app/views/cocktail/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="container">
  <h2><%= "Greetest cocktails" %></h2>
  <%= link_to "New Cocktail", new_cocktail_path %>
    <div class="row">
      <% @cocktails.each do |cocktail| %>
        <h3><%= link_to cocktail.name, cocktail %></h3>
      <% end %>
    </div>
</div>

app/views/cocktails/new.html.erb
<h1>Create a new cocktail</h1>
<div class="container">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<div class="container">
  <ul>
    <% @cocktail.doses.each do |dose| %>
      <% if dose.persisted? %>
        <li>
          <%= dose.description %> <%= dose.ingredient.name %>
          <%= link_to "&times;".html_safe, dose, method: :delete %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <hr>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
  <%= render 'navbar/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/navbar/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to cocktails_path, class: "navbar-wagon-brand" do %>
     KIKOU
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>